name: harsha_delights_sales
description: Sales team mobile app for Harsha Delights field operations
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  
  # HTTP & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # Local Storage & Database
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  
  # Location & Maps
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  
  # Firebase & Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.2
  logger: ^2.4.0
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.14
  
  # File handling
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  
  # PDF & Documents
  pdf: ^3.11.1
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
