# =====================================================================================
# HARSHA DELIGHTS PROMETHEUS CONFIGURATION
# =====================================================================================
# Production-ready Prometheus configuration for monitoring the confectionery system
# =====================================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'harsha-delights-dev'
    environment: 'development'

# Rule files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # ERPNext application metrics
  - job_name: 'erpnext'
    static_configs:
      - targets: ['erpnext:8000']
    scrape_interval: 30s
    metrics_path: /api/method/frappe.utils.health
    scrape_timeout: 10s

  # Medusa e-commerce backend metrics
  - job_name: 'medusa'
    static_configs:
      - targets: ['medusa:9000']
    scrape_interval: 15s
    metrics_path: /admin/metrics
    scrape_timeout: 5s

  # EspoCRM metrics (if available)
  - job_name: 'espocrm'
    static_configs:
      - targets: ['espocrm:80']
    scrape_interval: 30s
    metrics_path: /api/v1/health
    scrape_timeout: 10s

  # Nginx metrics (if enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # Database metrics via custom exporters
  - job_name: 'mariadb-exporter'
    static_configs:
      - targets: ['mariadb:3306']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      target: ['mariadb:3306']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      target: ['postgres:5432']

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:3000/health
        - http://erpnext:8000
        - http://medusa:9000/health
        - http://espocrm:80
        - http://nginx:80/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom business metrics (if implemented)
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['api-gateway:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/business
    scrape_timeout: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB

# Remote write configuration (for external systems)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "user"
#       password: "password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"

# Tracing configuration (if using distributed tracing)
# tracing:
#   endpoint: "jaeger:14268/api/traces"
#   insecure: true