apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-apps
  namespace: harsha-delights
  labels:
    app: frontend-apps
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-apps
  template:
    metadata:
      labels:
        app: frontend-apps
    spec:
      containers:
      - name: frontend-apps
        image: harsha-delights/frontend-apps:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: harsha-config
              key: api-url
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-apps-service
  namespace: harsha-delights
spec:
  selector:
    app: frontend-apps
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP